#!/bin/bash

# Parse the environment variables and auto-create the default.vcl file
/generate.sh

# Start varnish and log
varnishd -f /etc/varnish/default.vcl -s malloc,100M -a 0.0.0.0:${VARNISH_PORT}
sleep 5
varnishlog

